POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Alice",
  "password": "topsecret"
}

###

GET http://localhost:8080/auth/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxpY2UiLCJpYXQiOjE3Mzg3NjY2MjgsImV4cCI6MTczODg1MzAyOH0.YFtCv80KHE1GcX__XZB5V7kdApjiOzfAdUGw53YugIE

###
POST http://localhost:8080/auth-v2/login
Content-Type: application/json

{
  "login": "Alice",
  "pass": "topsecret"
}

###

GET http://localhost:8080/auth-v2/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxpY2UiLCJpYXQiOjE3Mzg3NjY2MjgsImV4cCI6MTczODg1MzAyOH0.YFtCv80KHE1GcX__XZB5V7kdApjiOzfAdUGw53YugIE
